app/models.py
from flask_login import UserMixin

class UserAuthModel(UserMixin):
    """
        User model for Flask Login 
    """
    def __init__(self, username, password):
        self.id = username
        self.password = password

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError
from .db_connection import get_user, validate_user_password

class AddTodoForm(FlaskForm):
    description = StringField("Descripción", validators=[DataRequired()])
    submit = SubmitField("Crear")

class ToDoOptionsForm(FlaskForm):
    description = StringField(validators=[DataRequired()]) 
    delete = SubmitField("Borrar")
    update = SubmitField("Actualizar estado")
    edit = SubmitField("Editar")
    save = SubmitField("Guardar")

class LogInForm(FlaskForm):
    username = StringField("Usuario", validators=[DataRequired()])
    password = PasswordField("Contraseña", validators=[DataRequired()])
    submit = SubmitField("Iniciar sesión")

    def validate_username(self, username):
        if not get_user(username.data):
            raise ValidationError("No existe ningún usuario registrado con ese nombre.")

    def validate_password(self, password):
        if get_user(self.username.data) and not validate_user_password(self.username.data, password.data):
            raise ValidationError("Contraseña incorrecta, por favor inténtelo de nuevo.")

class SignUpForm(FlaskForm):
    username = StringField("Usuario", validators=[DataRequired()])
    password = PasswordField("Contraseña", validators=[DataRequired(), EqualTo("confirm_password", message="Las contraseñas no coinciden.")])
    confirm_password = PasswordField("Confirmar contraseña", validators=[DataRequired(), EqualTo("password", message="Las contraseñas no coinciden.")])
    submit = SubmitField("Registrar")

    def validate_username(self, username):
        if get_user(username.data):
            raise ValidationError("El nombre de usuario ingresado ya ha sido registrado.")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .blueprints.auth import auth, login_manager
from .blueprints.todo_bp import todo_bp
import os
from dotenv import load_dotenv

def create_app():

    app = Flask(__name__, template_folder="../templates", static_folder="../static")

    load_dotenv()
    app.config['SECRET_KEY'] = os.getenv("FLASK_SECRET_KEY")
 
    app.register_blueprint(todo_bp)
    app.register_blueprint(auth)
    login_manager.init_app(app)

    bootstrap = Bootstrap(app)

    return app

app/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import LoginManager, login_user, login_required, logout_user
from ..models import UserAuthModel
from ..forms import LogInForm, SignUpForm
from ..db_connection import create_user, get_user
from werkzeug.security import generate_password_hash


auth = Blueprint('auth', __name__, url_prefix='/auth', template_folder="../../templates", static_folder="../../static")

login_manager = LoginManager()
login_manager.login_view = "auth.login"

@login_manager.user_loader
def load_user(user):

    user_data = get_user(user)

    return UserAuthModel(user_data["id"], user_data["password"])


@auth.route("/login", methods=["GET","POST"])
def login():

    login_form = LogInForm()

    if login_form.validate_on_submit():

        username = login_form.username.data
        user_data = get_user(username)

        user = UserAuthModel(user_data["id"], user_data["password"])

        login_user(user)

        return redirect(url_for("index"))

    context = {
        "login_form" : login_form
    }

    return render_template("login.html", **context)

@auth.route("/signup", methods=["GET","POST"])
def signup():

    signup_form = SignUpForm()

    if signup_form.validate_on_submit():

        username = signup_form.username.data
        password = generate_password_hash(signup_form.password.data)

        create_user(username, password)

        user = UserAuthModel(username, password)
        
        login_user(user)

        return redirect(url_for("index"))

    context = {
        "signup_form" : signup_form
    }

    return render_template("signup.html", **context)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

app/blueprints/todo_bp.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from ..db_connection import delete_todo, get_user_todo_list, put_todo, delete_todo, update_todo, edit_todo_description
from ..forms import AddTodoForm, ToDoOptionsForm

todo_bp = Blueprint('todo', __name__, url_prefix='/todo', template_folder="../../templates", static_folder="../../static")

@todo_bp.route("/todo_list", methods=["GET","POST"])
@login_required
def todo_list():

    username = current_user.id
    to_do_list = get_user_todo_list(username)
    
    add_todo_form = AddTodoForm()
    todo_options_form = ToDoOptionsForm()

    if add_todo_form.validate_on_submit(): 
        todo_description = add_todo_form.description.data
        put_todo(username,todo_description)
        
        return redirect(url_for("todo.todo_list"))

    context = {
        "add_todo_form" : add_todo_form,
        "to_do_list" : to_do_list,
        "todo_options_form" : todo_options_form
    }

    return render_template("todo_list.html", **context)

@todo_bp.route("/edit_todo/<todo_id>/<int:done>", methods=["POST"])
@login_required
def edit_todo(todo_id,done):

    username = current_user.id

    todo_options_form = ToDoOptionsForm()

    if todo_options_form.delete.data:
        delete_todo(username,todo_id)
    elif todo_options_form.update.data:
        update_todo(username,todo_id,done)
    elif todo_options_form.save.data:
        description = request.form.get("description")
        edit_todo_description(username,todo_id, description)

    return redirect(url_for("todo.todo_list"))

main.py
from flask import render_template
from flask_login import login_required, current_user
from app import create_app

app = create_app()

@app.route("/", methods=["GET","POST"])
@login_required
def index():
    
    username = current_user.id

    context = {
        "username" : username
    }

    return render_template("index.html", **context)

if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=5000)

templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
    {{ super() }}

    <title>
        {% block title %} Flask - To Do List | {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
{% endblock %}

{% block body %}

    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header"> 
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9" aria-expanded="false"> 
                    <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
                </button> 
                <h4 class="navbar-text">Flask - To Do List</h4> 
            </div> 
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-9" aria-expanded="false" style="height: 1px;"> 
                <ul class="nav navbar-nav"> 
                    {% block navbar_buttons %}
                    {% endblock %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    {% block scripts %}
        {{ super() }}
    {% endblock %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title  %}
    {{ super() }}
    Index
{% endblock %}

{% block navbar_buttons %}
    <li class="active"><a href="{{ url_for('index') }}">Inicio</a></li> 
    <li><a href= "{{ url_for('todo.todo_list') }}" >Tareas</a></li>
    <li><a href="{{ url_for('auth.logout') }}">Cerrar sesión</a></li> 
{% endblock %}

{% block content %}

<div class="container">
    <div class="user-welcome-form">
        <div class="list-group-item" style="border-radius: 20px; padding: 50px 60px; text-align: justify;">
            <h1 style="font-size: 34px;">Bienvenido, {{ username.capitalize() }}!</h1>
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('todo.todo_list') }}" role="button"> Ver To Do List</a></p>
        </div>
    </div>
</div>
        
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title  %}
    {{ super() }}
    Log In
{% endblock %}

{% block navbar_buttons %}
    <li class="active"><a href= "{{ url_for('auth.login') }}" >Iniciar sesión</a></li>
    <li><a href="{{ url_for('auth.signup') }}">Registrarse</a></li> 
{% endblock %}


{% block content %}
    
    <div class="container">
        
        <div class="user-auth-form">
            <h3 style="font-size: 35px;"> Inicia sesión: </h3>
            <div class="list-group-item" style="border-radius: 10px; padding: 30px;">
                {{ wtf.quick_form(login_form) }}
            </div>
        </div>
            
    </div>

{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title  %}
    {{ super() }}
    Sign Up
{% endblock %}

{% block navbar_buttons %}
    <li class="active"><a href="{{ url_for('auth.signup') }}">Registrarse</a></li> 
    <li><a href= "{{ url_for('auth.login') }}" >Iniciar sesión</a></li>
{% endblock %}


{% block content %}
    
    <div class="container">
        
        <div class="user-auth-form">
            <h3 style="font-size: 35px;"> Registrate: </h3>
            <div class="list-group-item" style="border-radius: 10px; padding: 30px;">
                {{ wtf.quick_form(signup_form) }}
            </div>
        </div>
            
    </div>

{% endblock %}

templates/todo_list.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title  %}
    {{ super() }}
    To Do List
{% endblock %}

{% block navbar_buttons %}
    <li><a href="{{ url_for('index') }}">Inicio</a></li> 
    <li class="active"><a href= "{{ url_for('todo.todo_list') }}" >Tareas</a></li>
    <li><a href="{{ url_for('auth.logout') }}">Cerrar sesión</a></li> 
{% endblock %}

{% block content %}
    
    <div class="container">
        
        <section class="add-task-form">
            <h3> Agregar una nueva tarea: </h3>
            <div class="list-group-item" style="border-radius: 15px;">
                {{ wtf.quick_form(add_todo_form) }}
            </div>
        </section>
        
        {% if to_do_list %}
            <section class="list-group tasks">
                <h3> Tareas: </h3>
                {% for todo in to_do_list %}
                    <li class="list-group-item" style="border-radius: 15px;">
                        
                        {% if todo.to_dict().done %}
                            <span class="badge" style="background-color: #32a72e;"> Done </span>
                        {% else %}
                            <span class="badge" style="background-color: #b80d0d;"> To do </span>
                        {% endif %}

                        <form class="edit-todo-form" method="POST" action='{{ url_for("todo.edit_todo", todo_id=todo.id, done=todo.to_dict().done) }}'>
                            {{ todo_options_form.description(id="todo-description", class="todo-description", value = todo.to_dict().description, readonly = True) }}                        
                            {{ todo_options_form.delete(class="btn btn-default") }}
                            {{ todo_options_form.update(class="btn btn-default") }}
                            {{ todo_options_form.edit(type="button", class="btn btn-default") }}
                            {{ todo_options_form.save(class="btn btn-default") }}       
                        </form>
                   
                    </li>
                {% endfor %}
            </section>
        {% endif %}
        
    </div>

{% endblock %}
    
{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/todo_list.js')}}"></script>
{% endblock %}